runtime: python27
api_version: 1
threadsafe: true
env_variables:  
  DJANGO_SETTINGS_MODULE: 'webapps.settings'
libraries:
- name: django
  version: "1.5"
- name: webapp2
  version: "2.5.2"
builtins:
- django_wsgi: on

handlers:
- url: /static
  static_dir: static
  expiration: '0'
# This handler tells app engine how to route requests to a WSGI application.
# The script value is in the format <path.to.module>.<wsgi_application>
# where <wsgi_application> is a WSGI application object.
- url: /webapp2/.*  # This regex directs all routes to main.app
  script: services.main.app
